# forgeui_generated.cmake — auto-generated by ForgeUI CodeGen; do not edit manually.
# Include from preview or SDK CMakeLists: include("${FORGEUI_CODEGEN_DIR}/forgeui_generated.cmake")

get_filename_component(FORGEUI_GENERATED_DIR "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY)

file(GLOB_RECURSE FORGEUI_GENERATOR_SOURCES "${FORGEUI_GENERATED_DIR}/*.c")

file(GLOB_RECURSE FORGEUI_HEADER_FILES "${FORGEUI_GENERATED_DIR}/*.h")
get_filename_component(FORGEUI_GENERATED_ROOT "${FORGEUI_GENERATED_DIR}" ABSOLUTE)
set(FORGEUI_GENERATOR_INCLUDE_DIRS "${FORGEUI_GENERATED_ROOT}")
foreach(header_file ${FORGEUI_HEADER_FILES})
  get_filename_component(header_dir ${header_file} DIRECTORY)
  get_filename_component(header_dir_abs ${header_dir} ABSOLUTE)
  if(NOT "${header_dir_abs}" STREQUAL "${FORGEUI_GENERATED_ROOT}")
    list(APPEND FORGEUI_GENERATOR_INCLUDE_DIRS ${header_dir_abs})
  endif()
endforeach()
if(FORGEUI_GENERATOR_INCLUDE_DIRS)
  list(REMOVE_DUPLICATES FORGEUI_GENERATOR_INCLUDE_DIRS)
endif()

list(LENGTH FORGEUI_GENERATOR_SOURCES FORGEUI_GENERATOR_SOURCE_COUNT)
message(STATUS "ForgeUI Generated: ${FORGEUI_GENERATOR_SOURCE_COUNT} source(s) in ${FORGEUI_GENERATED_DIR}")
