import type { LoadedProject } from "@forgeui/core";
import type { Diagnostic } from "@forgeui/shared";
import fs from "node:fs";
import path from "node:path";

/** FR-055: emit a MicroPython preview module (subset). */
export function emitMicroPython(
  loaded: LoadedProject,
  outDir: string,
  diagnostics: Diagnostic[],
): string[] {
  if (!loaded.project.export?.micropython) return [];

  fs.mkdirSync(outDir, { recursive: true });
  const pyPath = path.join(outDir, "ui.py");
  const screens = [...loaded.screens.entries()]
    .map(([id, doc]) => {
      const kids = (doc.children ?? [])
        .map((c) => `        # ${c.type} id=${c.id} name=${JSON.stringify(c.name)}`)
        .join("\n");
      return `def create_screen_${id}():\n    # screen ${id}\n${kids || "    pass"}\n`;
    })
    .join("\n");

  const py = `# Auto-generated by ForgeUI CodeGen (FR-055 MicroPython export)
# Preview / scripting aid — not a full LVGL MicroPython binding.

ENTRY = ${JSON.stringify(loaded.project.entrySymbol)}
DEFAULT_SCREEN = ${JSON.stringify(loaded.project.defaultScreen)}
DISPLAY = (${loaded.project.display.width}, ${loaded.project.display.height}, ${loaded.project.display.colorDepth})

${screens}
def ui_init():
    create_screen_${loaded.project.defaultScreen}()
`;

  fs.writeFileSync(pyPath, py, "utf8");
  diagnostics.push({
    level: "info",
    code: "E_MPY_OK",
    message: `MicroPython → forgeui_generated/micropython/ui.py`,
  });
  return [pyPath];
}
