# forgeui_generated.cmake — auto-generated by ForgeUI CodeGen; do not edit manually.
# Include from preview or SDK CMakeLists: include("${FORGEUI_CODEGEN_DIR}/forgeui_generated.cmake")
# Sources are listed explicitly so image/*.c and fonts/*.c always link (do not rely on stale GLOB cache).

get_filename_component(FORGEUI_GENERATED_DIR "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY)

set(FORGEUI_GENERATOR_SOURCES
  "${FORGEUI_GENERATED_DIR}/custom/custom_func.c"
  "${FORGEUI_GENERATED_DIR}/custom/ui_events.c"
  "${FORGEUI_GENERATED_DIR}/fonts/font_2312_v9_16.c"
  "${FORGEUI_GENERATED_DIR}/fonts/font_SourceHanSansCN-Bold_16.c"
  "${FORGEUI_GENERATED_DIR}/screens/screen_home.c"
  "${FORGEUI_GENERATED_DIR}/screens/screen_settings.c"
  "${FORGEUI_GENERATED_DIR}/ui.c"
  "${FORGEUI_GENERATED_DIR}/ui_nav.c"
)

# Safety net: pick up any .c added outside CodeGen list (triggers reconfigure on CMake ≥3.12).
file(GLOB_RECURSE FORGEUI_GENERATOR_SOURCES_GLOB CONFIGURE_DEPENDS "${FORGEUI_GENERATED_DIR}/*.c")
if(FORGEUI_GENERATOR_SOURCES_GLOB)
  list(APPEND FORGEUI_GENERATOR_SOURCES ${FORGEUI_GENERATOR_SOURCES_GLOB})
  list(REMOVE_DUPLICATES FORGEUI_GENERATOR_SOURCES)
endif()

file(GLOB_RECURSE FORGEUI_HEADER_FILES CONFIGURE_DEPENDS "${FORGEUI_GENERATED_DIR}/*.h")
get_filename_component(FORGEUI_GENERATED_ROOT "${FORGEUI_GENERATED_DIR}" ABSOLUTE)
set(FORGEUI_GENERATOR_INCLUDE_DIRS "${FORGEUI_GENERATED_ROOT}")
foreach(header_file ${FORGEUI_HEADER_FILES})
  get_filename_component(header_dir ${header_file} DIRECTORY)
  get_filename_component(header_dir_abs ${header_dir} ABSOLUTE)
  if(NOT "${header_dir_abs}" STREQUAL "${FORGEUI_GENERATED_ROOT}")
    list(APPEND FORGEUI_GENERATOR_INCLUDE_DIRS ${header_dir_abs})
  endif()
endforeach()
if(FORGEUI_GENERATOR_INCLUDE_DIRS)
  list(REMOVE_DUPLICATES FORGEUI_GENERATOR_INCLUDE_DIRS)
endif()

list(LENGTH FORGEUI_GENERATOR_SOURCES FORGEUI_GENERATOR_SOURCE_COUNT)
message(STATUS "ForgeUI Generated: ${FORGEUI_GENERATOR_SOURCE_COUNT} source(s) in ${FORGEUI_GENERATED_DIR}")
