import { spawn, spawnSync } from "node:child_process";

import fs from "node:fs";

import path from "node:path";

import { fileURLToPath } from "node:url";

import { generate } from "@forgeui/codegen";

import { codegenArtifactsReady, openProject } from "@forgeui/core";

import { Diagnostic, ErrorCodes } from "@forgeui/shared";

import { writePreviewIr } from "./wasm/forge-bridge.js";

import { buildWasmLvgl } from "./wasm-emcc.js";

import type {

  PreviewBackend,

  PreviewBuildLogSink,

  PreviewPrepareResult,

  PreviewRunResult,

  PreviewSession,

} from "./types.js";



function resolveRepoRoot(): string {

  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");

}



function resolveWasmTemplate(): string {

  const candidates = [

    path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../../templates/wasm-sim"),

    path.resolve(process.cwd(), "templates/wasm-sim"),

  ];

  for (const c of candidates) {

    if (fs.existsSync(path.join(c, "index.html"))) return c;

  }

  throw new Error("templates/wasm-sim not found");

}



function resolveSdlTemplate(): string {

  const candidates = [

    path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../../templates/sdl-sim"),

    path.resolve(process.cwd(), "templates/sdl-sim"),

  ];

  for (const c of candidates) {

    if (fs.existsSync(path.join(c, "CMakeLists.txt"))) return c;

  }

  throw new Error("templates/sdl-sim not found");

}



function copyFile(src: string, dest: string): void {

  fs.mkdirSync(path.dirname(dest), { recursive: true });

  if (fs.existsSync(dest)) {

    const a = fs.readFileSync(src);

    const b = fs.readFileSync(dest);

    if (a.length === b.length && a.equals(b)) return;

  }

  fs.copyFileSync(src, dest);

}



function resolveLvglRoot(): string | null {

  const env = process.env.FORGEUI_LVGL_ROOT;

  if (env && fs.existsSync(path.join(env, "lvgl.h"))) return path.resolve(env);

  if (env && fs.existsSync(path.join(env, "lvgl", "lvgl.h"))) return path.resolve(env);

  const repo = resolveRepoRoot();

  for (const c of [

    path.join(repo, "xos-package/lvgl"),

    path.join(repo, "third_party/lvgl"),

  ]) {

    if (fs.existsSync(path.join(c, "lvgl.h"))) return c;

  }

  return null;

}



function resolveEmcc(): string | null {

  const env = process.env.FORGEUI_EMSCRIPTEN_ROOT ?? process.env.EMSCRIPTEN;

  if (env) {

    const emcc = path.join(env, process.platform === "win32" ? "emcc.bat" : "emcc");

    if (fs.existsSync(emcc)) return emcc;

  }

  const probe = process.platform === "win32" ? "where" : "which";

  const hit = spawnSync(probe, ["emcc"], { encoding: "utf8" });

  if (hit.status === 0) {

    const line = (hit.stdout ?? "").split(/\r?\n/).find((l) => l.trim());

    if (line?.trim()) return line.trim();

  }

  return null;

}



function writeConfigHeader(buildDir: string, width: number, height: number, colorDepth: number): void {

  const content = `/* Auto-generated by ForgeUI PreviewHost — do not edit */

#ifndef FORGEUI_PREVIEW_CONFIG_H

#define FORGEUI_PREVIEW_CONFIG_H

#define FORGEUI_HOR_RES ${width}

#define FORGEUI_VER_RES ${height}

#define FORGEUI_COLOR_DEPTH ${colorDepth}

#endif

`;

  fs.writeFileSync(path.join(buildDir, "forgeui_preview_config.h"), content, "utf8");

}



function patchLvConf(buildDir: string, colorDepth: number): void {

  const confPath = path.join(buildDir, "lv_conf.h");

  if (!fs.existsSync(confPath)) return;

  const text = fs.readFileSync(confPath, "utf8");

  let next = text.replace(/#define LV_COLOR_DEPTH\s+\d+/, `#define LV_COLOR_DEPTH ${colorDepth}`);

  next = next.replace(/#define LV_USE_ASSERT_MEM_INTEGRITY\s+\d+/, "#define LV_USE_ASSERT_MEM_INTEGRITY 0");

  next = next.replace(/#define LV_USE_ASSERT_OBJ\s+\d+/, "#define LV_USE_ASSERT_OBJ 0");

  next = next.replace(/#define LV_USE_ASSERT_STYLE\s+\d+/, "#define LV_USE_ASSERT_STYLE 0");

  if (next !== text) fs.writeFileSync(confPath, next, "utf8");

}



function openPreviewPage(buildDir: string, logLine: (line: string) => void): string {

  const modePath = path.join(buildDir, "preview-mode.json");

  if (fs.existsSync(modePath)) {

    try {

      const mode = JSON.parse(fs.readFileSync(modePath, "utf8")) as { mode?: string; html?: string };

      if (mode.mode === "lvgl-wasm" && mode.html) {

        const lvglHtml = path.join(buildDir, mode.html);

        if (fs.existsSync(lvglHtml)) {

          logLine(`打开 LVGL Wasm 预览: ${lvglHtml}`);

          return lvglHtml;

        }

      }

    } catch {

      /* fall through to IR shell */

    }

  }

  const indexHtml = path.join(buildDir, "index.html");

  logLine(`打开 Wasm IR 预览: ${indexHtml}`);

  return indexHtml;

}



function openInBrowser(filePath: string): void {

  const abs = path.resolve(filePath);

  const url = `file:///${abs.replace(/\\/g, "/")}`;

  if (process.platform === "win32") {

    spawn("cmd", ["/c", "start", "", url], { detached: true, stdio: "ignore" }).unref();

  } else if (process.platform === "darwin") {

    spawn("open", [url], { detached: true, stdio: "ignore" }).unref();

  } else {

    spawn("xdg-open", [url], { detached: true, stdio: "ignore" }).unref();

  }

}



export class WasmBackend implements PreviewBackend {

  readonly id = "wasm" as const;



  async prepare(

    projectRoot: string,

    opts: { fetchSdl?: boolean; skipGenerate?: boolean } = {},

  ): Promise<PreviewPrepareResult> {

    const diagnostics: Diagnostic[] = [];

    const root = path.resolve(projectRoot);

    const loaded = openProject(root);

    const artifactsMissing = !codegenArtifactsReady(root, loaded.project);

    if (!opts.skipGenerate || artifactsMissing) {

      if (opts.skipGenerate && artifactsMissing) {

        diagnostics.push({

          level: "info",

          code: "E_GEN_AUTO",

          message: "生成物缺失，自动执行 generate…",

        });

      }

      const gen = await generate(root);

      diagnostics.push(...gen.diagnostics);

      if (!gen.ok) {

        return { ok: false, buildDir: "", diagnostics, canBuild: false };

      }

    }



    const buildDir = path.join(root, ".forge", "preview-wasm");

    fs.mkdirSync(buildDir, { recursive: true });



    const tpl = resolveWasmTemplate();

    const sdlTpl = resolveSdlTemplate();

    for (const name of ["index.html", "preview-shell.js", "CMakeLists.txt", "main.c", "README.md"]) {

      const src = path.join(tpl, name);

      if (fs.existsSync(src)) copyFile(src, path.join(buildDir, name));

    }

    for (const name of ["hal.c", "hal.h", "lv_conf.h", "optimize_drivers.cmake"]) {

      const src = path.join(sdlTpl, name);

      if (fs.existsSync(src)) copyFile(src, path.join(buildDir, name));

    }



    writeConfigHeader(

      buildDir,

      loaded.project.display.width,

      loaded.project.display.height,

      loaded.project.display.colorDepth,

    );

    patchLvConf(buildDir, loaded.project.display.colorDepth);



    writePreviewIr(root, buildDir);



    const cache = {

      projectRoot: root,

      lvglVersion: loaded.project.lvglVersion,

      previewBackend: "wasm",

      preparedAt: new Date().toISOString(),

    };

    fs.writeFileSync(path.join(buildDir, "preview-meta.json"), `${JSON.stringify(cache, null, 2)}\n`);



    const emcc = resolveEmcc();

    const lvglRoot = resolveLvglRoot();

    const canBuild = Boolean(emcc && lvglRoot);



    if (emcc) {

      fs.writeFileSync(path.join(buildDir, "emcc.path"), `${emcc}\n`, "utf8");

      diagnostics.push({ level: "info", code: "E_PREV_WASM", message: `Emscripten: ${emcc}` });

    } else {

      diagnostics.push({

        level: "info",

        code: "E_PREV_WASM_IR",

        message: "未检测到 emcc；将使用 IR 浏览器预览。安装 Emscripten + LVGL 后可编译真 LVGL Wasm。",

      });

    }

    if (lvglRoot) {

      fs.writeFileSync(path.join(buildDir, "lvgl.root"), `${lvglRoot}\n`, "utf8");

    } else {

      diagnostics.push({

        level: "warning",

        code: ErrorCodes.E_PREV_001,

        message: "未找到 LVGL 源码（npm run fetch:lvgl），Emscripten 编译不可用",

      });

    }



    diagnostics.push({

      level: "info",

      code: "E_PREV_PREPARED",

      message: `Wasm 预览目录: ${buildDir}`,

      path: buildDir,

    });



    return { ok: true, buildDir, diagnostics, canBuild };

  }



  async start(

    projectRoot: string,

    opts: {

      prepareOnly?: boolean;

      buildOnly?: boolean;

      runOnly?: boolean;

      wait?: boolean;

      skipGenerate?: boolean;

      onBuildLog?: PreviewBuildLogSink;

    } = {},

  ): Promise<PreviewRunResult> {

    const wallStart = Date.now();

    const buildLogs: string[] = [];

    const logLine = (line: string) => {

      buildLogs.push(line);

      opts.onBuildLog?.(line);

    };



    const root = path.resolve(projectRoot);

    const buildDir = path.join(root, ".forge", "preview-wasm");



    if (opts.runOnly && !opts.buildOnly && !opts.prepareOnly) {

      const previewHtml = openPreviewPage(buildDir, logLine);

      if (!fs.existsSync(previewHtml)) {

        return {

          ok: false,

          diagnostics: [

            {

              level: "error",

              code: ErrorCodes.E_PREV_001,

              message: "未找到 Wasm 预览，请先执行「编译」或「生成+编译+模拟运行」",

            },

          ],

          buildLogs,

        };

      }

      openInBrowser(previewHtml);

      const session: PreviewSession = {

        backendId: this.id,

        buildDir,

        logs: buildLogs,

      };

      const lvgl = previewHtml.includes("forgeui_preview");

      return {

        ok: true,

        session,

        diagnostics: [

          {

            level: "info",

            code: "E_PREV_STARTED",

            message: lvgl ? "已在浏览器打开 LVGL Wasm 预览" : "已在浏览器打开 Wasm IR 预览",

          },

        ],

        buildLogs,

        elapsedMs: Date.now() - wallStart,

      };

    }



    const prepared = await this.prepare(root, { skipGenerate: opts.skipGenerate });

    if (!prepared.ok) {

      return { ok: false, diagnostics: prepared.diagnostics, buildLogs };

    }

    for (const d of prepared.diagnostics) logLine(`[${d.level}] ${d.message}`);



    if (opts.prepareOnly) {

      return {

        ok: true,

        session: { backendId: this.id, buildDir: prepared.buildDir, logs: buildLogs },

        diagnostics: prepared.diagnostics,

        buildLogs,

      };

    }



    writePreviewIr(root, prepared.buildDir);

    logLine("已刷新 preview-ir.json");



    let wasmBuilt = false;

    if (prepared.canBuild) {

      const emccPath = fs.readFileSync(path.join(prepared.buildDir, "emcc.path"), "utf8").trim();

      wasmBuilt = await buildWasmLvgl({

        prepared,

        projectRoot: root,

        emccPath,

        logLine,

        diagnostics: prepared.diagnostics,

      });

    } else if (opts.buildOnly) {

      logLine("[wasm] Emscripten/LVGL 不可用，保留 IR shell");

    }



    if (opts.buildOnly) {

      const elapsedMs = Date.now() - wallStart;

      logLine(`[timing] wasm prepare+build: ${elapsedMs}ms`);

      return {

        ok: wasmBuilt || !prepared.canBuild,

        session: { backendId: this.id, buildDir: prepared.buildDir, logs: buildLogs },

        diagnostics: prepared.diagnostics,

        buildLogs,

        elapsedMs,

      };

    }



    const previewHtml = openPreviewPage(prepared.buildDir, logLine);

    openInBrowser(previewHtml);

    return {

      ok: true,

      session: { backendId: this.id, buildDir: prepared.buildDir, logs: buildLogs },

      diagnostics: [

        ...prepared.diagnostics,

        {

          level: "info",

          code: "E_PREV_STARTED",

          message: wasmBuilt ? "已在浏览器打开 LVGL Wasm 预览" : "已在浏览器打开 Wasm IR 预览",

        },

      ],

      buildLogs,

      elapsedMs: Date.now() - wallStart,

    };

  }



  async stop(_session: PreviewSession): Promise<void> {

    /* Browser tab — nothing to kill */

  }

}


